import { Inter } from 'next/font/google';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={
                    inter.className +
                    ' max-425:text-sm md:text-lg lg:text-xl xl:text-2xl '
                }
            >
                {children}
            </body>
        </html>
    );
}
