import { Inter, Roboto } from 'next/font/google';
import { Toaster } from 'react-hot-toast';
import './globals.css';

const inter = Inter({ subsets: ['latin'] });
const roboto = Roboto({
    subsets: ['latin'],
    weight: ['500'],
    variable: '--roboto-font',
});
const fonts = inter.className + ' ' + roboto.variable;

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body
                className={
                    fonts +
                    ' max-425:text-xs 425:text-sm md:text-base lg:text-lg 1152:text-xl'
                }
                suppressHydrationWarning={true}
            >
                {children}
                <Toaster
                    toastOptions={{
                        success: {
                            style: {
                                background: '#dcfce7',
                                color: '#15803d',
                                fontSize: '.8rem',
                                padding: '1rem',
                                border: '1px solid #4ade80',
                            },
                            iconTheme: {
                                primary: '#4ade80',
                                secondary: '#15803d',
                            },
                        },
                        error: {
                            style: {
                                background: '#fee2e2',
                                color: '#f87171',
                                fontSize: '.8rem',
                                padding: '1rem',
                                border: '1px solid #fca5a5',
                            },
                            iconTheme: {
                                primary: '#f87171',
                                secondary: '#dc2626',
                            },
                        },
                    }}
                />
            </body>
        </html>
    );
}
